# Generated by Django 5.2.7 on 2025-12-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historialmovimiento',
            new_name='auditoria_h_fecha_h_3e8a9d_idx',
            old_name='auditoria_h_fecha_h_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimiento',
            new_name='auditoria_h_tipo_ev_08c944_idx',
            old_name='auditoria_h_tipo_ev_9d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimiento',
            new_name='auditoria_h_usuario_6269c3_idx',
            old_name='auditoria_h_usuario_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimiento',
            new_name='auditoria_h_nivel_5db312_idx',
            old_name='auditoria_h_nivel_4d5e6f_idx',
        ),
        migrations.AlterField(
            model_name='historialmovimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
