# Generated by Django 5.2.7 on 2025-12-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_rename_auditoria_h_fecha_h_8a1b2c_idx_auditoria_h_fecha_h_3e8a9d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo_evento',
            field=models.CharField(choices=[('VENTA_CREADA', 'Venta Creada'), ('VENTA_EDITADA', 'Venta Editada'), ('VENTA_ELIMINADA', 'Venta Eliminada'), ('COTIZACION_CREADA', 'Cotización Creada'), ('COTIZACION_EDITADA', 'Cotización Editada'), ('COTIZACION_ELIMINADA', 'Cotización Eliminada'), ('COTIZACION_CONVERTIDA', 'Cotización Convertida a Venta'), ('ABONO_REGISTRADO', 'Abono Registrado'), ('ABONO_CONFIRMADO', 'Abono Confirmado'), ('ABONO_ELIMINADO', 'Abono Eliminado'), ('CLIENTE_CREADO', 'Cliente Creado'), ('CLIENTE_EDITADO', 'Cliente Editado'), ('CLIENTE_ELIMINADO', 'Cliente Eliminado'), ('USUARIO_CREADO', 'Usuario Creado'), ('USUARIO_EDITADO', 'Usuario Editado'), ('USUARIO_ELIMINADO', 'Usuario Eliminado'), ('USUARIO_LOGIN', 'Usuario Inició Sesión'), ('USUARIO_LOGOUT', 'Usuario Cerró Sesión'), ('KILOMETROS_ACUMULADOS', 'Kilómetros Acumulados'), ('KILOMETROS_REDIMIDOS', 'Kilómetros Redimidos'), ('PROMOCION_APLICADA', 'Promoción Aplicada'), ('PROMOCION_CREADA', 'Promoción Creada'), ('PROMOCION_EDITADA', 'Promoción Editada'), ('PROMOCION_ELIMINADA', 'Promoción Eliminada'), ('PROVEEDOR_CREADO', 'Proveedor Creado'), ('PROVEEDOR_EDITADO', 'Proveedor Editado'), ('PROVEEDOR_ELIMINADO', 'Proveedor Eliminado'), ('EJECUTIVO_CREADO', 'Ejecutivo Creado'), ('EJECUTIVO_EDITADO', 'Ejecutivo Editado'), ('EJECUTIVO_ELIMINADO', 'Ejecutivo Eliminado'), ('CONFIRMACION_SUBIDA', 'Confirmación Subida'), ('CONFIRMACION_ELIMINADA', 'Confirmación Eliminada'), ('LOGISTICA_ACTUALIZADA', 'Logística Actualizada'), ('OTRO', 'Otro Evento')], db_index=True, max_length=50, verbose_name='Tipo de Evento'),
        ),
    ]
