"""
Django settings for agencia_web project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Sentry (monitoreo de errores en producción) - importación condicional
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except ImportError:
    sentry_sdk = None
    DjangoIntegration = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env si existe (python-dotenv)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SEGURO: Sin fallback hardcodeado - requiere variable de entorno
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# SEGURO: Por defecto False - requiere explícitamente 'True', '1' o 'yes'
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Validar SECRET_KEY según el entorno
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-only-insecure-key-change-in-production'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set in production environment')

# Hosts permitidos - usar variable de entorno en producción
# SEGURO: Sin fallback hardcodeado - requiere variable de entorno en producción
_allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_str.split(',') if h.strip()]

if not ALLOWED_HOSTS:
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        raise ImproperlyConfigured('ALLOWED_HOSTS must be set in production environment')

# Orígenes confiables para CSRF (necesario para HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://movums.com.mx',
    'https://www.movums.com.mx',
    'https://n8n.movums.com.mx',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Aplicaciones de Terceros ---
    'django.contrib.humanize',
    'widget_tweaks',  # Se mantiene porque se usa en algunos templates
    
    # 🚨 CONFIGURACIÓN DE CRISPY FORMS (NUEVO)
    'crispy_forms',
    'crispy_bootstrap5',
    
    # --- Aplicaciones Locales del Proyecto ---
    'usuarios',             # Módulo de Perfil y Rol
    'crm',                  # Módulo de Clientes
    'ventas',               # Módulo de Ventas, Pagos, Logística y Reportes
    'auditoria',            # Módulo de Auditoría e Historial de Movimientos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agencia_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS apunta a la carpeta 'templates' en la raíz del proyecto para el dashboard.html
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.user_rol_safe',
            ],
        },
    },
]

WSGI_APPLICATION = 'agencia_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# IMPORTANTE: La elección de BD depende SOLO de DB_ENGINE (nunca de DEBUG).
# Local: en .env dejar DB_ENGINE comentado → SQLite. Servidor: DB_ENGINE=postgresql en .env → PostgreSQL.
if os.environ.get('DB_ENGINE') == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT'),
            # OPTIMIZACIÓN: Reutilizar conexiones por 60 segundos
            # Reduce overhead de crear conexiones nuevas en cada request
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Configuración de Email
# En desarrollo (DEBUG=True), usar backend de consola
# En producción (DEBUG=False), usar SMTP real
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@movums.com.mx')
    SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Tiempo de espera para conexiones SMTP (en segundos)
EMAIL_TIMEOUT = 10


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-mx' # Establece el idioma predeterminado a español de México

TIME_ZONE = 'America/Mexico_City' # Establece la zona horaria de México

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde Django recopila los archivos estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales donde buscar archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Busca la carpeta 'static' en la raíz del proyecto
]

# Configuración de WhiteNoise para servir archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =============================================================================
# Límites de Upload (Hardening - Protección de memoria del servidor)
# =============================================================================
# Tope máximo de la petición completa (POST data + archivos)
# Debe ser >= al archivo más grande permitido (10 MB en validators.py)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# Si el archivo supera este tamaño, se escribe a disco temporal en lugar de RAM
# Esto protege la memoria del servidor contra archivos grandes
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440   # 2.5 MB

# Número máximo de campos en un formulario (protección contra DoS)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Número máximo de archivos en una sola petición
DATA_UPLOAD_MAX_NUMBER_FILES = 20

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuraciones de seguridad para producción (solo cuando DEBUG = False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS - HTTP Strict Transport Security
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookies de sesión adicionales
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Strict'


# --- Configuraciones de Autenticación y Login ---

# URL a la que se redirige después de un login exitoso.
LOGIN_REDIRECT_URL = '/' 

# URL a la que se redirige si un usuario no loggeado intenta acceder a una vista protegida.
LOGIN_URL = '/login/'
# URL posterior al logout (por consistencia con la vista LogoutView)
LOGOUT_REDIRECT_URL = '/login/'

# 🚨 CONFIGURACIONES DE CRISPY FORMS (NUEVO)
# Indica a Crispy Forms qué framework de CSS usar por defecto.
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

# Define el template pack por defecto para todo el proyecto.
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Configuración de Logging
# Asegurar que el directorio de logs existe
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {name} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django-errors.log'),
            'maxBytes': 1024 * 1024 * 15,  # 15 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ventas': {
            'handlers': ['file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'crm': {
            'handlers': ['file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'usuarios': {
            'handlers': ['file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'auditoria': {
            'handlers': ['file', 'error_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Configuración de Email
# En desarrollo (DEBUG=True), usar backend de consola
# En producción (DEBUG=False), usar SMTP real
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@movums.com.mx')
    SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Tiempo de espera para conexiones SMTP (en segundos)
EMAIL_TIMEOUT = 10

# -----------------------------------------------------------------------------
# Sentry - Monitoreo de errores en producción (solo si SENTRY_DSN está en .env)
# -----------------------------------------------------------------------------
if os.environ.get("SENTRY_DSN") and sentry_sdk is not None:
    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,  # Reducido para producción
        send_default_pii=False,  # SEGURO: No enviar datos personales
    )
