# Generated by Django 5.2.7 on 2025-10-22 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('C1', 'Contrato Tipo 1'), ('C2', 'Contrato Tipo 2'), ('C3', 'Contrato Tipo 3')], default='C1', max_length=2)),
                ('tipo_vuelo', models.CharField(choices=[('IDA', 'Solo Ida'), ('RED', 'Redondo'), ('HOS', 'Solo Hospedaje'), ('TRP', 'Transporte y Hospedaje')], max_length=3)),
                ('fecha_inicio_viaje', models.DateField()),
                ('fecha_fin_viaje', models.DateField(blank=True, null=True)),
                ('costo_neto', models.DecimalField(decimal_places=2, help_text='Costo real del viaje para la agencia.', max_digits=10)),
                ('costo_venta_final', models.DecimalField(decimal_places=2, help_text='Precio total que paga el cliente.', max_digits=10)),
                ('saldo_restante', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tipo_cambio_usd', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbonoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_anticipo', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('recibo_pdf', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='ventas.ventaviaje')),
            ],
        ),
    ]
