# Generated by Django 5.2.7 on 2025-10-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventaviaje_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuelo_confirmado', models.BooleanField(default=False, verbose_name='Vuelo Confirmado')),
                ('hospedaje_reservado', models.BooleanField(default=False, verbose_name='Hospedaje Reservado')),
                ('seguro_emitido', models.BooleanField(default=False, verbose_name='Seguro de Viaje Emitido')),
                ('documentos_enviados', models.BooleanField(default=False, verbose_name='Documentación Enviada al Cliente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistica', to='ventas.ventaviaje')),
            ],
            options={
                'verbose_name': 'Registro de Logística',
                'verbose_name_plural': 'Registros de Logística',
            },
        ),
    ]
