# Generated by Django 5.2.7 on 2025-10-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cliente_apellido_cliente_fecha_actualizacion_and_more'),
        ('ventas', '0003_logistica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonopago',
            name='es_anticipo',
        ),
        migrations.AddField(
            model_name='abonopago',
            name='forma_pago',
            field=models.CharField(choices=[('TRN', 'Transferencia'), ('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('PPL', 'PayPal/Digital')], default='TRN', max_length=3),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_asociadas', to='crm.cliente', verbose_name='Cliente Asociado'),
        ),
    ]
