# Generated by Django 5.2.7 on 2025-10-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_abonopago_es_anticipo_abonopago_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistica',
            name='vuelo_confirmado',
            field=models.BooleanField(default=False, verbose_name='Vuelo/Transporte Confirmado'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_vuelo',
            field=models.CharField(choices=[('IDA', 'Solo Ida'), ('RED', 'Redondo'), ('HOS', 'Solo Hospedaje'), ('TRP', 'Transporte y Hospedaje')], max_length=3, verbose_name='Tipo de Viaje'),
        ),
    ]
