# Generated by Django 5.2.7 on 2025-10-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_logistica_vuelo_confirmado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaviaje',
            name='saldo_restante',
        ),
    ]
