# Generated by Django 5.2.7 on 2025-11-06 03:17

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_ventaviaje_saldo_restante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Plantilla')),
                ('tipo', models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional'), ('OTROS', 'Otros')], max_length=5, unique=True, verbose_name='Tipo de Contrato')),
                ('contenido_base', models.TextField(help_text='Usar variables de sustitución en formato Python como {cliente_nombre_completo}, {costo_total}, etc.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
            },
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='cantidad_apertura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad para Aperturar el Viaje'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='documentos_cliente',
            field=models.FileField(blank=True, null=True, upload_to='documentos_cliente/%Y/%m/%d/', verbose_name='Documentos del Cliente (Zip/PDF)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_circuito_int',
            field=models.BooleanField(default=False, verbose_name='Circuito Internacional'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_crucero',
            field=models.BooleanField(default=False, verbose_name='Crucero'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_hospedaje',
            field=models.BooleanField(default=False, verbose_name='Hospedaje'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_paquete',
            field=models.BooleanField(default=False, verbose_name='Paquete Todo Incluido'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_renta_auto',
            field=models.BooleanField(default=False, verbose_name='Renta de Auto'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_seguro',
            field=models.BooleanField(default=False, verbose_name='Seguro de Viaje'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_tour',
            field=models.BooleanField(default=False, verbose_name='Tour/Excursión'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_tramite_pasaporte',
            field=models.BooleanField(default=False, verbose_name='Trámite de Pasaporte'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_tramite_visa',
            field=models.BooleanField(default=False, verbose_name='Trámite de Visa'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_traslado',
            field=models.BooleanField(default=False, verbose_name='Traslado (Transporte terrestre)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicio_vuelo',
            field=models.BooleanField(default=False, verbose_name='Vuelo'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], default='NAC', max_length=3, verbose_name='Tipo de Viaje (Contrato)'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='fecha_pago',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='fecha_fin_viaje',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Regreso (Fin de Viaje)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='fecha_inicio_viaje',
            field=models.DateField(verbose_name='Fecha de Ida (Inicio de Viaje)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_vuelo',
            field=models.CharField(choices=[('IDA', 'Solo Ida'), ('RED', 'Redondo'), ('HOS', 'Solo Hospedaje'), ('TRP', 'Transporte y Hospedaje')], max_length=3, verbose_name='Tipo de Viaje/Vuelo'),
        ),
        migrations.CreateModel(
            name='ContratoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_final', models.TextField(verbose_name='Contrato Final')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='ventas.ventaviaje')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.contratoplantilla', verbose_name='Plantilla Base Utilizada')),
            ],
            options={
                'verbose_name': 'Contrato Generado',
                'verbose_name_plural': 'Contratos Generados',
            },
        ),
    ]
