# Generated by Django 5.2.7 on 2025-11-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_contratoplantilla_ventaviaje_cantidad_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratogenerado',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Archivo PDF del Contrato'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug único para la URL del viaje.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='plantilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.contratoplantilla', verbose_name='Plantilla Base Utilizada'),
        ),
    ]
