# Generated by Django 5.2.7 on 2025-11-06 05:35

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_contratogenerado_archivo_pdf_ventaviaje_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonopago',
            options={'verbose_name': 'Abono o Pago', 'verbose_name_plural': 'Abonos y Pagos'},
        ),
        migrations.AlterModelOptions(
            name='ventaviaje',
            options={'verbose_name': 'Venta de Viaje', 'verbose_name_plural': 'Ventas de Viajes'},
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='fecha_vencimiento_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Pago Total'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='fecha_pago',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='forma_pago',
            field=models.CharField(choices=[('TRN', 'Transferencia'), ('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('PPL', 'PayPal/Digital')], default='TRN', max_length=3, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Abono'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='recibo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recibos/', verbose_name='Recibo/Comprobante'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='ventas.ventaviaje', verbose_name='Venta Asociada'),
        ),
        migrations.AlterField(
            model_name='contratogenerado',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='ventas.ventaviaje', verbose_name='Venta Asociada'),
        ),
        migrations.AlterField(
            model_name='contratoplantilla',
            name='tipo',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional'), ('OTROS', 'Otros')], max_length=5, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='documentos_enviados',
            field=models.BooleanField(default=False, verbose_name='Documentación Final Enviada al Cliente'),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistica', to='ventas.ventaviaje', verbose_name='Venta Asociada'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='cantidad_apertura',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad de Apertura/Anticipo'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_cambio_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=6, verbose_name='Tipo de Cambio (USD)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_contrato',
            field=models.CharField(choices=[('C1', 'Contrato Tipo 1'), ('C2', 'Contrato Tipo 2'), ('C3', 'Contrato Tipo 3')], default='C1', max_length=2, verbose_name='Tipo de Contrato Interno'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], default='NAC', max_length=3, verbose_name='Tipo de Viaje (Plantilla de Contrato)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
