# Generated by Django 5.2.7 on 2025-11-06 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_abonopago_options_alter_ventaviaje_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonopago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha del Pago'),
        ),
    ]
