# Generated by Django 5.2.7 on 2025-11-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_abonopago_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_circuito_int',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_crucero',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_hospedaje',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_paquete',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_renta_auto',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_seguro',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_tour',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_tramite_pasaporte',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_tramite_visa',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_traslado',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='servicio_vuelo',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='tipo_cambio_usd',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='tipo_contrato',
        ),
        migrations.RemoveField(
            model_name='ventaviaje',
            name='tipo_vuelo',
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='pasajeros',
            field=models.TextField(blank=True, help_text='Ingresa el nombre completo de cada pasajero, separados por línea nueva o coma.', verbose_name='Pasajeros (Nombres Completos para Contrato)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='servicios_detalle',
            field=models.TextField(blank=True, help_text='Incluye los servicios contratados (vuelo, hospedaje, tours, etc.)', verbose_name='Servicios del Viaje (Detalle y Descripción)'),
        ),
    ]
