# Generated by Django 5.2.7 on 2025-11-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_remove_ventaviaje_servicio_circuito_int_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='servicios_seleccionados',
            field=models.CharField(blank=True, choices=[('VLO', 'Vuelo (Boleto de Avión)'), ('HOS', 'Hospedaje (Hotel/Airbnb)'), ('TRN', 'Traslados Aeropuerto/Hotel'), ('SEG', 'Seguro de Viaje'), ('CRS', 'Crucero'), ('ASS', 'Asistencia/Soporte 24/7'), ('EXC', 'Excursiones/Tours'), ('REN', 'Renta de Auto')], help_text='Selecciona los servicios que forman parte de esta venta.', max_length=255, verbose_name='Servicios Incluidos (Selección Múltiple)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='servicios_detalle',
            field=models.TextField(blank=True, help_text='Incluye los detalles específicos (fechas, aerolíneas, hoteles, etc.)', verbose_name='Servicios del Viaje (Detalle y Descripción)'),
        ),
    ]
