# Generated by Django 5.2.7 on 2025-11-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_ventaviaje_servicios_seleccionados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaviaje',
            name='servicios_seleccionados',
            field=models.TextField(blank=True, help_text='Lista de códigos de servicios separados por comas. (VLO, HOS, etc.)', verbose_name='Servicios Incluidos (Selección Múltiple)'),
        ),
    ]
