# Generated by Django 5.2.7 on 2025-11-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_ventaviaje_servicios_seleccionados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaviaje',
            name='servicios_detalle',
            field=models.TextField(blank=True, help_text='Incluye los detalles específicos (fechas, aerolíneas, hoteles, etc.) de los servicios contratados.', verbose_name='Servicios del Viaje (Detalle y Descripción)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='servicios_seleccionados',
            field=models.TextField(blank=True, choices=[('VUE', 'Vuelo'), ('HOS', 'Hospedaje'), ('TRA', 'Traslado (Transporte terrestre)'), ('TOU', 'Tour/Excursión'), ('CIR', 'Circuito Internacional'), ('REN', 'Renta de Auto'), ('PAQ', 'Paquete Todo Incluido'), ('CRU', 'Crucero'), ('SEG', 'Seguro de Viaje'), ('OTR', 'Otros Servicios')], help_text='Códigos de servicios seleccionados separados por coma.', verbose_name='Servicios Incluidos (Selección Múltiple)'),
        ),
    ]
