# Generated by Django 5.2.7 on 2025-11-10 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_ventaviaje_servicios_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonopago',
            name='fecha_pago',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='contratoplantilla',
            name='contenido_base',
            field=models.TextField(help_text='Usar variables de sustitución en formato Django Template como {{ cliente_nombre_completo }}, {{ costo_total_localizado }}, etc.'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='servicios_seleccionados',
            field=models.TextField(blank=True, choices=[('VUE', 'Vuelo'), ('HOS', 'Hospedaje'), ('TRA', 'Traslado (Transporte terrestre)'), ('TOU', 'Tour/Excursión'), ('CIR', 'Circuito Internacional'), ('REN', 'Renta de Auto'), ('PAQ', 'Paquete Todo Incluido'), ('CRU', 'Crucero'), ('SEG', 'Seguro de Viaje'), ('OTR', 'Otros Servicios')], help_text='Códigos de servicios seleccionados separados por coma (ej. VUE,HOS).', verbose_name='Servicios Incluidos (Selección Múltiple)'),
        ),
    ]
