# Generated by Django 5.2.7 on 2025-11-11 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_abonopago_fecha_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoplantilla',
            name='contenido_base',
            field=models.TextField(help_text='Usar variables de sustitución en formato Python como {cliente_nombre_completo}, {costo_total}, etc.'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ABONO', 'Abono Registrado'), ('LIQUIDACION', 'Venta Liquidada'), ('APERTURA', 'Apertura Registrada'), ('LOGISTICA', 'Cambio en Logística')], max_length=20, verbose_name='Tipo de Notificación')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('vista', models.BooleanField(default=False, verbose_name='Vista')),
                ('fecha_vista', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vista')),
                ('usuario', models.ForeignKey(limit_choices_to={'perfil__rol': 'JEFE'}, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ventas.ventaviaje', verbose_name='Venta Relacionada')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'vista'], name='ventas_noti_usuario_477103_idx'), models.Index(fields=['-fecha_creacion'], name='ventas_noti_fecha_c_378e76_idx')],
            },
        ),
    ]
