# Generated by Django 5.2.7 on 2025-11-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_contratoplantilla_contenido_base_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proveedor')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('ejecutivo', models.CharField(blank=True, max_length=255, verbose_name='Ejecutivo a Cargo')),
                ('servicio', models.CharField(choices=[('VUELOS', 'Vuelos'), ('HOTELES', 'Hoteles'), ('TOURS', 'Tours'), ('TODO', 'Todo')], max_length=10, verbose_name='Servicio que Ofrece')),
                ('link', models.URLField(blank=True, verbose_name='Link del Proveedor')),
                ('genera_factura', models.BooleanField(default=False, verbose_name='Genera Factura Automática')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
