# Generated by Django 5.2.7 on 2025-11-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_asociadas', to='ventas.proveedor', verbose_name='Proveedor Asignado'),
        ),
    ]
