# Generated by Django 5.2.7 on 2025-11-13 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_ventaviaje_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='confirmaciones/%Y/%m/%d/', verbose_name='Archivo de Confirmación')),
                ('nota', models.CharField(blank=True, max_length=255, verbose_name='Descripción / Nota')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmaciones_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='ventas.ventaviaje', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Confirmación de Venta',
                'verbose_name_plural': 'Confirmaciones de Venta',
                'ordering': ('-fecha_subida',),
            },
        ),
    ]
