# Generated by Django 5.2.7 on 2025-11-15 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_confirmacionventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=25, verbose_name='Teléfono de Contacto')),
                ('ubicacion_asignada', models.CharField(max_length=150, verbose_name='Ubicación Asignada')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='ejecutivos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documentos Personales (PDF)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ejecutivo',
                'verbose_name_plural': 'Ejecutivos',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
