# Generated by Django 5.2.7 on 2025-11-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_ejecutivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutivo',
            name='email',
            field=models.EmailField(blank=True, help_text='Será usado para crear sus credenciales.', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecutivo_asociado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
    ]
