# Generated by Django 5.2.7 on 2025-11-15 23:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_ejecutivo_email_ejecutivo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutivo',
            name='sueldo_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='Sueldo Base'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='ultima_contrasena',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Última Contraseña Asignada'),
        ),
    ]
