# Generated by Django 5.2.7 on 2025-11-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_ejecutivo_sueldo_base_ejecutivo_ultima_contrasena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonopago',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado por Contador'),
        ),
        migrations.AddField(
            model_name='abonopago',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='abonopago',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'CONTADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='abono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ventas.abonopago', verbose_name='Abono Relacionado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'CONTADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='estado_confirmacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CONFIRMACION', 'En Confirmación'), ('COMPLETADO', 'Completado')], default='PENDIENTE', help_text='Estado de confirmación del pago por el contador', max_length=20, verbose_name='Estado de Confirmación'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='modo_pago_apertura',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TRN', 'Transferencia'), ('TAR', 'Tarjeta')], default='EFE', help_text='Modo de pago del anticipo/apertura', max_length=3, verbose_name='Modo de Pago de Apertura'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ABONO', 'Abono Registrado'), ('LIQUIDACION', 'Venta Liquidada'), ('APERTURA', 'Apertura Registrada'), ('LOGISTICA', 'Cambio en Logística'), ('PAGO_PENDIENTE', 'Pago Pendiente de Confirmación'), ('PAGO_CONFIRMADO', 'Pago Confirmado por Contador')], max_length=20, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
