# Generated by Django 5.2.7 on 2025-11-24 23:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_abonopago_confirmado_abonopago_confirmado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='costo_modificacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo adicional por modificar la venta. Se suma al costo total.', max_digits=10, verbose_name='Costo de Modificación'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', help_text='Estado general de la venta', max_length=20, verbose_name='Estado de la Venta'),
        ),
    ]
