# Generated by Django 5.2.7 on 2025-11-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_add_estado_y_costo_modificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ABONO', 'Abono Registrado'), ('LIQUIDACION', 'Venta Liquidada'), ('APERTURA', 'Apertura Registrada'), ('LOGISTICA', 'Cambio en Logística'), ('PAGO_PENDIENTE', 'Pago Pendiente de Confirmación'), ('PAGO_CONFIRMADO', 'Pago Confirmado por Contador'), ('CANCELACION', 'Venta Cancelada')], max_length=20, verbose_name='Tipo de Notificación'),
        ),
        migrations.CreateModel(
            name='PlantillaConfirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VUELO_UNICO', 'Vuelo Único'), ('VUELO_REDONDO', 'Vuelo Redondo'), ('HOSPEDAJE', 'Hospedaje'), ('TRASLADO', 'Traslado'), ('GENERICA', 'Genérica (Cualquier captura)')], max_length=20, verbose_name='Tipo de Plantilla')),
                ('datos', models.JSONField(default=dict, help_text='Almacena todos los campos llenados de la plantilla en formato JSON', verbose_name='Datos de la Plantilla')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_confirmacion', to='ventas.ventaviaje', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Plantilla de Confirmación',
                'verbose_name_plural': 'Plantillas de Confirmación',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['venta', 'tipo'], name='ventas_plan_venta_i_7fa15e_idx'), models.Index(fields=['-fecha_creacion'], name='ventas_plan_fecha_c_f11bf4_idx')],
            },
        ),
    ]
