# Generated by Django 5.2.7 on 2025-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_agregar_plantilla_confirmacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistica',
            name='documentos_enviados',
        ),
        migrations.RemoveField(
            model_name='logistica',
            name='seguro_emitido',
        ),
        migrations.AddField(
            model_name='logistica',
            name='tickets_confirmado',
            field=models.BooleanField(default=False, verbose_name='Tickets Confirmados'),
        ),
        migrations.AddField(
            model_name='logistica',
            name='traslado_confirmado',
            field=models.BooleanField(default=False, verbose_name='Traslado Confirmado'),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='vuelo_confirmado',
            field=models.BooleanField(default=False, verbose_name='Vuelo Confirmado'),
        ),
        migrations.AlterField(
            model_name='plantillaconfirmacion',
            name='tipo',
            field=models.CharField(choices=[('VUELO_UNICO', 'Vuelo Sencillo'), ('VUELO_REDONDO', 'Vuelo Redondo'), ('HOSPEDAJE', 'Hospedaje'), ('TRASLADO', 'Traslado'), ('GENERICA', 'Genérica (Cualquier captura)')], max_length=20, verbose_name='Tipo de Plantilla'),
        ),
    ]
