# Generated by Django 5.2.7 on 2025-11-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_cambiar_campos_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecutivo',
            name='tipo_vendedor',
            field=models.CharField(choices=[('OFICINA', 'Ejecutivo de Ventas Internas'), ('CALLE', 'Ejecutivo de Ventas de Campo')], default='OFICINA', help_text='Determina el sistema de comisiones: Ventas Internas (escalonado) o Ventas de Campo (4% fijo)', max_length=10, verbose_name='Tipo de Vendedor'),
        ),
    ]
