# Generated by Django 5.2.7 on 2025-11-30 01:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_ejecutivo_tipo_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='aplica_descuento_kilometros',
            field=models.BooleanField(default=False, help_text='Marca si se otorgó un descuento promocional del 10%.', verbose_name='Aplicar descuento Kilómetros Movums'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='descuento_kilometros_mxn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se calcula automáticamente como el 10% del precio final.', max_digits=10, verbose_name='Monto de descuento Kilómetros Movums'),
        ),
    ]
