# Generated by Django 5.2.7 on 2025-12-01 18:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_ventaviaje_aplica_descuento_kilometros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servicio', models.CharField(choices=[('VUE', 'Vuelo'), ('HOS', 'Hospedaje'), ('TRA', 'Traslado (Transporte terrestre)'), ('TOU', 'Tour/Excursión'), ('CIR', 'Circuito Internacional'), ('REN', 'Renta de Auto'), ('PAQ', 'Paquete Todo Incluido'), ('CRU', 'Crucero'), ('SEG', 'Seguro de Viaje'), ('OTR', 'Otros Servicios')], max_length=5, verbose_name='Código de Servicio')),
                ('nombre_servicio', models.CharField(max_length=120, verbose_name='Nombre mostrado')),
                ('monto_planeado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto planificado')),
                ('pagado', models.BooleanField(default=False, verbose_name='Servicio pagado')),
                ('fecha_pagado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas internas')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_logisticos', to='ventas.ventaviaje', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Servicio logístico',
                'verbose_name_plural': 'Servicios logísticos',
                'ordering': ['orden', 'pk'],
                'unique_together': {('venta', 'codigo_servicio')},
            },
        ),
    ]
