# Generated by Django 5.2.7 on 2025-12-08 23:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_agregar_campos_logistica_faltantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistica',
            name='documentos_enviados',
        ),
        migrations.RemoveField(
            model_name='logistica',
            name='seguro_emitido',
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='impuestos_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Impuestos en dólares americanos para ventas internacionales.', max_digits=10, null=True, verbose_name='Impuestos (USD)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='suplementos_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Suplementos en dólares americanos para ventas internacionales.', max_digits=10, null=True, verbose_name='Suplementos (USD)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='tarifa_base_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Tarifa base en dólares americanos para ventas internacionales.', max_digits=10, null=True, verbose_name='Tarifa Base (USD)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Tipo de cambio del día para convertir dólares a pesos mexicanos.', max_digits=10, null=True, verbose_name='Tipo de Cambio (USD a MXN)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='tours_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Tours en dólares americanos para ventas internacionales.', max_digits=10, null=True, verbose_name='Tours (USD)'),
        ),
    ]
