# Generated by Django 5.2.7 on 2025-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_agregar_campos_venta_internacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaviaje',
            name='modo_pago_apertura',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TRN', 'Transferencia'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito')], default='EFE', help_text='Modo de pago del anticipo/apertura', max_length=3, verbose_name='Modo de Pago de Apertura'),
        ),
    ]
