# Generated by Django 5.2.7 on 2025-12-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0032_agregar_deposito_modo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonopago',
            name='monto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='abonopago',
            name='tipo_cambio_aplicado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Tipo de Cambio aplicado'),
        ),
    ]
