# Generated by Django 5.2.7 on 2025-12-15 17:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_promocionkilometros_factor_multiplicador_and_more'),
        ('ventas', '0033_abonopago_monto_usd_abonopago_tipo_cambio_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='descuento_promociones_mxn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento total por promociones'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='resumen_promociones',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen de promociones aplicadas'),
        ),
        migrations.CreateModel(
            name='VentaPromocionAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promocion', models.CharField(max_length=150)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('combinable_snapshot', models.BooleanField(default=True)),
                ('requiere_confirmacion_snapshot', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_venta', to='crm.promocionkilometros')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_aplicadas', to='ventas.ventaviaje')),
            ],
            options={
                'verbose_name': 'Promoción aplicada a venta',
                'verbose_name_plural': 'Promociones aplicadas a ventas',
            },
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='promociones',
            field=models.ManyToManyField(blank=True, related_name='ventas_aplicadas', through='ventas.VentaPromocionAplicada', to='crm.promocionkilometros'),
        ),
    ]
