# Generated by Django 5.2.7 on 2025-12-15 17:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_ventaviaje_descuento_promociones_mxn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapromocionaplicada',
            name='km_bono',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
