# Generated by Django 5.2.7 on 2025-12-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_ventapromocionaplicada_km_bono'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='descuento_promociones_aplicado_como_pago',
            field=models.BooleanField(default=False, verbose_name='Descuento de promociones registrado en abonos'),
        ),
    ]
