# Generated by Django 5.2.7 on 2025-12-16 22:36

from django.db import migrations, models


def migrar_servicios(apps, schema_editor):
    """Migra los datos del campo 'servicio' al nuevo campo 'servicios'."""
    Proveedor = apps.get_model('ventas', 'Proveedor')
    for proveedor in Proveedor.objects.all():
        if hasattr(proveedor, 'servicio') and proveedor.servicio:
            # Migrar el valor del campo antiguo al nuevo campo
            proveedor.servicios = proveedor.servicio
            proveedor.save()


def revertir_servicios(apps, schema_editor):
    """Revertir la migración: tomar el primer servicio de 'servicios' y ponerlo en 'servicio'."""
    Proveedor = apps.get_model('ventas', 'Proveedor')
    for proveedor in Proveedor.objects.all():
        if proveedor.servicios:
            # Tomar el primer servicio de la lista
            servicios_list = [s.strip() for s in proveedor.servicios.split(',') if s.strip()]
            if servicios_list:
                proveedor.servicio = servicios_list[0]
                proveedor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0036_ventaviaje_descuento_promociones_aplicado_como_pago'),
    ]

    operations = [
        # 1. Agregar los nuevos campos primero
        migrations.AddField(
            model_name='proveedor',
            name='email_ejecutivo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Ejecutivo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='servicios',
            field=models.TextField(blank=True, help_text='Códigos de servicios seleccionados separados por coma (ej. VUELOS,HOTELES,TOURS).', verbose_name='Servicios que Ofrece (Selección Múltiple)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_ejecutivo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contacto del Ejecutivo'),
        ),
        # 2. Migrar los datos del campo antiguo al nuevo
        migrations.RunPython(migrar_servicios, revertir_servicios),
        # 3. Eliminar el campo antiguo
        migrations.RemoveField(
            model_name='proveedor',
            name='servicio',
        ),
    ]
