# Generated by Django 5.2.7 on 2025-12-17 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0037_agregar_campos_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abonopago',
            name='comprobante_imagen',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante (recibo, screenshot, ticket). Obligatorio para Transferencia, Tarjeta y Depósito.', null=True, upload_to='comprobantes_pagos/%Y/%m/%d/', verbose_name='Comprobante de Pago (Imagen)'),
        ),
        migrations.AddField(
            model_name='abonopago',
            name='comprobante_subido',
            field=models.BooleanField(default=False, help_text='Indica si el comprobante ya fue subido al servidor.', verbose_name='Comprobante Subido'),
        ),
        migrations.AddField(
            model_name='abonopago',
            name='comprobante_subido_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Subida del Comprobante'),
        ),
        migrations.AddField(
            model_name='abonopago',
            name='comprobante_subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Comprobante Subido Por'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='comprobante_apertura',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante del pago de apertura. Obligatorio para Transferencia, Tarjeta y Depósito.', null=True, upload_to='comprobantes_apertura/%Y/%m/%d/', verbose_name='Comprobante de Apertura (Imagen)'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='comprobante_apertura_subido',
            field=models.BooleanField(default=False, help_text='Indica si el comprobante de apertura ya fue subido al servidor.', verbose_name='Comprobante Apertura Subido'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='comprobante_apertura_subido_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Subida del Comprobante de Apertura'),
        ),
        migrations.AddField(
            model_name='ventaviaje',
            name='comprobante_apertura_subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_apertura_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Comprobante Apertura Subido Por'),
        ),
    ]
