# Generated by Django 5.2.7 on 2025-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_agregar_campos_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='folio',
            field=models.CharField(blank=True, help_text='Identificador único de la venta. Formato: SERVICIO-AAAAMMDD-XX', max_length=20, null=True, unique=True, verbose_name='Folio de Venta'),
        ),
        migrations.AlterField(
            model_name='logisticaservicio',
            name='codigo_servicio',
            field=models.CharField(choices=[('VUE', 'Vuelo'), ('HOS', 'Hospedaje'), ('ALO', 'Alojamiento Alterno'), ('TRA', 'Traslado'), ('TOU', 'Tour y Actividades'), ('CIR', 'Circuito Internacional'), ('REN', 'Renta de Auto'), ('PAQ', 'Paquete'), ('CRU', 'Crucero'), ('SEG', 'Seguro de Viaje'), ('DOC', 'Trámites de Documentación'), ('OTR', 'Otros Servicios')], max_length=5, verbose_name='Código de Servicio'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='servicios_seleccionados',
            field=models.TextField(blank=True, choices=[('VUE', 'Vuelo'), ('HOS', 'Hospedaje'), ('ALO', 'Alojamiento Alterno'), ('TRA', 'Traslado'), ('TOU', 'Tour y Actividades'), ('CIR', 'Circuito Internacional'), ('REN', 'Renta de Auto'), ('PAQ', 'Paquete'), ('CRU', 'Crucero'), ('SEG', 'Seguro de Viaje'), ('DOC', 'Trámites de Documentación'), ('OTR', 'Otros Servicios')], help_text='Códigos de servicios seleccionados separados por coma (ej. VUE,HOS).', verbose_name='Servicios Incluidos (Selección Múltiple)'),
        ),
    ]
