# Generated by Django 5.2.7 on 2025-12-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_agregar_folio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='condiciones_comerciales',
            field=models.TextField(blank=True, help_text='Términos, condiciones y acuerdos comerciales con el proveedor', null=True, verbose_name='Condiciones Comerciales'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
