# Generated by Django 5.2.7 on 2025-12-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_proveedor_condiciones_comerciales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecutivo',
            name='tipo_vendedor',
            field=models.CharField(choices=[('MOSTRADOR', 'Asesor de Mostrador'), ('CAMPO', 'Asesor de Campo'), ('ISLA', 'Asesor de Isla')], default='MOSTRADOR', help_text='Determina el sistema de comisiones: Asesor de Mostrador, Campo o Isla', max_length=10, verbose_name='Tipo de Asesor'),
        ),
    ]
