# Generated by Django 5.2.7 on 2025-12-19 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_migrar_tipos_ejecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutivo',
            name='documento_pdf',
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='acta_nacimiento',
            field=models.FileField(blank=True, help_text='Sube el acta de nacimiento en formato PDF o imagen (JPG, PNG)', null=True, upload_to='ejecutivos/documentos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Acta de Nacimiento'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, help_text='Sube el comprobante de domicilio en formato PDF o imagen (JPG, PNG)', null=True, upload_to='ejecutivos/documentos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante de Domicilio'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha en que el ejecutivo ingresó a la empresa', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del ejecutivo', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='ine_imagen',
            field=models.FileField(blank=True, help_text='Sube la identificación oficial (INE) en formato PDF o imagen (JPG, PNG)', null=True, upload_to='ejecutivos/documentos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='INE'),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='oficina',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Oficina'),
        ),
    ]
