# Generated by Django 5.2.7 on 2025-12-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0044_migrar_ubicacion_a_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaviaje',
            name='modo_pago_apertura',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TRN', 'Transferencia'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('LIG', 'Liga de Pago'), ('PRO', 'Directo a Proveedor')], default='EFE', help_text='Modo de pago del anticipo/apertura', max_length=3, verbose_name='Modo de Pago de Apertura'),
        ),
    ]
