# Generated by Django 5.2.7 on 2025-12-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0049_backfill_cotizacion_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonopago',
            name='forma_pago',
            field=models.CharField(choices=[('TRN', 'Transferencia'), ('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('PPL', 'PayPal/Digital'), ('LIG', 'Liga de Pago'), ('PRO', 'Directo a Proveedor')], default='TRN', max_length=3, verbose_name='Forma de Pago'),
        ),
    ]
