# Generated by Django 5.2.7 on 2026-01-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0050_alter_abonopago_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonopago',
            name='requiere_factura',
            field=models.BooleanField(default=False, help_text='Indica si el cliente requiere factura por este abono.', verbose_name='Requiere Factura'),
        ),
    ]
