# Generated by Django 5.2.7 on 2026-01-03 00:45

import django.db.models.deletion
from django.db import migrations, models


def migrar_oficinas_a_objetos(apps, schema_editor):
    """
    Migra los valores de texto del campo 'oficina' en Ejecutivo
    a objetos Oficina y actualiza el campo temporal oficina_temp_id.
    """
    from django.db import connection
    
    Ejecutivo = apps.get_model('ventas', 'Ejecutivo')
    Oficina = apps.get_model('ventas', 'Oficina')
    
    # Usar SQL directo para obtener valores únicos del campo CharField
    # Primero verificar si el campo temporal existe, si no, usar el campo original
    with connection.cursor() as cursor:
        try:
            cursor.execute("""
                SELECT DISTINCT oficina 
                FROM ventas_ejecutivo 
                WHERE oficina IS NOT NULL AND oficina != ''
            """)
            oficinas_texto = [row[0].strip() for row in cursor.fetchall() if row[0] and row[0].strip()]
        except Exception:
            # Si hay error, intentar con el ORM
            ejecutivos = Ejecutivo.objects.exclude(oficina__isnull=True).exclude(oficina='')
            oficinas_texto = list(set([e.oficina.strip() for e in ejecutivos if e.oficina and e.oficina.strip()]))
    
    # Crear objetos Oficina para cada valor único
    oficinas_creadas = {}
    for nombre_oficina in oficinas_texto:
        if nombre_oficina:
            # Crear oficina con datos mínimos
            oficina, created = Oficina.objects.get_or_create(
                nombre=nombre_oficina,
                defaults={
                    'direccion': f'Dirección de {nombre_oficina}',
                    'ubicacion': 'Ubicación pendiente',
                    'responsable': 'Pendiente',
                    'encargado': 'Pendiente',
                    'tipo': 'PROPIA',
                    'activa': True,
                }
            )
            oficinas_creadas[nombre_oficina] = oficina
    
    # Actualizar el campo temporal oficina_temp_id en los ejecutivos
    # Usar el ORM en lugar de SQL directo para evitar problemas de compatibilidad
    for nombre_oficina, oficina in oficinas_creadas.items():
        Ejecutivo.objects.filter(oficina=nombre_oficina).update(oficina_temp_id=oficina.id)


def actualizar_ejecutivos_con_oficinas(apps, schema_editor):
    """
    Actualiza los ejecutivos para que apunten a las oficinas creadas.
    Se ejecuta después de cambiar el campo a ForeignKey.
    Usa el campo temporal oficina_temp_id para actualizar el ForeignKey.
    """
    from django.db import connection
    
    # Actualizar ejecutivos usando el campo temporal
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE ventas_ejecutivo 
            SET oficina_id = oficina_temp_id 
            WHERE oficina_temp_id IS NOT NULL
        """)


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión.
    """
    Oficina = apps.get_model('ventas', 'Oficina')
    Oficina.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0051_agregar_requiere_factura_abono'),
    ]

    operations = [
        # Primero crear el modelo Oficina
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único que identifica la oficina', max_length=255, unique=True, verbose_name='Nombre de la Oficina')),
                ('direccion', models.TextField(help_text='Dirección completa (punto en el mapa)', verbose_name='Dirección')),
                ('ubicacion', models.CharField(help_text='Descripción de ubicación dentro de plaza/edificio (ej: Local 15, Piso 2, Oficina 201)', max_length=255, verbose_name='Ubicación')),
                ('responsable', models.CharField(help_text='Nombre del responsable de la oficina', max_length=255, verbose_name='Responsable')),
                ('encargado', models.CharField(help_text='Nombre del encargado de la oficina', max_length=255, verbose_name='Encargado')),
                ('tipo', models.CharField(choices=[('PROPIA', 'Propia'), ('FRANQUICIA', 'Franquicia')], help_text='Indica si la oficina es propia o franquicia', max_length=20, verbose_name='Tipo de Oficina')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la oficina está activa', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nombre'],
            },
        ),
        # Agregar campo temporal para almacenar el ID de oficina
        migrations.AddField(
            model_name='ejecutivo',
            name='oficina_temp_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Migrar datos: crear oficinas desde valores de texto existentes y actualizar campo temporal
        migrations.RunPython(migrar_oficinas_a_objetos, revertir_migracion),
        # Cambiar el campo de CharField a ForeignKey
        migrations.AlterField(
            model_name='ejecutivo',
            name='oficina',
            field=models.ForeignKey(blank=True, help_text='Oficina a la que pertenece el ejecutivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecutivos', to='ventas.oficina', verbose_name='Oficina'),
        ),
        # Actualizar ejecutivos para que apunten a las oficinas usando el campo temporal
        migrations.RunPython(actualizar_ejecutivos_con_oficinas, migrations.RunPython.noop),
        # Eliminar campo temporal
        migrations.RemoveField(
            model_name='ejecutivo',
            name='oficina_temp_id',
        ),
    ]
