# Generated by Django 5.2.7 on 2026-01-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0052_crear_oficina_y_convertir_ejecutivo_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaviaje',
            name='modo_pago_apertura',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TRN', 'Transferencia'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('LIG', 'Liga de Pago'), ('PRO', 'Directo a Proveedor'), ('CRE', 'Crédito')], default='EFE', help_text='Modo de pago del anticipo/apertura', max_length=3, verbose_name='Modo de Pago de Apertura'),
        ),
    ]
