# Generated by Django 5.2.7 on 2026-01-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0050_alter_abonopago_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaservicio',
            name='opcion_proveedor',
            field=models.CharField(blank=True, help_text='Ej: Aerolínea, Hotel, etc.', max_length=255, verbose_name='Opción elegida del proveedor'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='comprobante_apertura',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante del pago de apertura. Obligatorio para Transferencia, Tarjeta y Depósito. No aplica para Crédito.', null=True, upload_to='comprobantes_apertura/%Y/%m/%d/', verbose_name='Comprobante de Apertura (Imagen)'),
        ),
    ]
