# Generated by Django 5.2.7 on 2026-01-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0053_agregar_credito_modo_pago'),
        ('ventas', '0054_agregar_opcion_proveedor_logistica'),
    ]

    operations = [
    ]
