# Generated by Django 5.2.7 on 2026-01-18 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0055_merge_20260118_1335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonopago',
            name='forma_pago',
            field=models.CharField(choices=[('TRN', 'Transferencia'), ('EFE', 'Ikki'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('PPL', 'PayPal/Digital'), ('LIG', 'Liga de Pago'), ('PRO', 'Directo a Proveedor')], default='TRN', max_length=3, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ABONO', 'Abono Registrado'), ('LIQUIDACION', 'Venta Liquidada'), ('APERTURA', 'Apertura Registrada'), ('LOGISTICA', 'Cambio en Logística'), ('PAGO_PENDIENTE', 'Pago Pendiente de Confirmación'), ('PAGO_CONFIRMADO', 'Pago Confirmado por Contador'), ('CANCELACION', 'Venta Cancelada'), ('SOLICITUD_ABONO_PROVEEDOR', 'Solicitud de Abono a Proveedor'), ('ABONO_PROVEEDOR_APROBADO', 'Abono a Proveedor Aprobado'), ('ABONO_PROVEEDOR_COMPLETADO', 'Abono a Proveedor Completado'), ('ABONO_PROVEEDOR_CANCELADO', 'Abono a Proveedor Cancelado')], max_length=35, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='modo_pago_apertura',
            field=models.CharField(choices=[('EFE', 'Ikki'), ('TRN', 'Transferencia'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('LIG', 'Liga de Pago'), ('PRO', 'Directo a Proveedor'), ('CRE', 'Crédito')], default='EFE', help_text='Modo de pago del anticipo/apertura', max_length=3, verbose_name='Modo de Pago de Apertura'),
        ),
        migrations.CreateModel(
            name='AbonoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto a Abonar')),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en USD')),
                ('tipo_cambio_aplicado', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio usado para convertir MXN a USD', max_digits=12, null=True, verbose_name='Tipo de Cambio Aplicado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('nota_solicitud', models.TextField(blank=True, help_text='Notas o comentarios sobre el abono solicitado', verbose_name='Nota de Solicitud')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('comprobante', models.ImageField(blank=True, help_text='Imagen del comprobante de pago al proveedor', null=True, upload_to='comprobantes_proveedor/%Y/%m/%d/', verbose_name='Comprobante de Abono')),
                ('nota_confirmacion', models.TextField(blank=True, help_text='Notas adicionales al confirmar el abono', verbose_name='Nota de Confirmación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_proveedor_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_proveedor_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado Por')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_proveedor_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_recibidos', to='ventas.proveedor', verbose_name='Proveedor')),
                ('solicitud_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_proveedor_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_proveedor', to='ventas.ventaviaje', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Abono a Proveedor',
                'verbose_name_plural': 'Abonos a Proveedores',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='abono_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ventas.abonoproveedor', verbose_name='Abono a Proveedor Relacionado'),
        ),
        migrations.AddIndex(
            model_name='abonoproveedor',
            index=models.Index(fields=['venta', 'estado'], name='ventas_abon_venta_i_05201b_idx'),
        ),
        migrations.AddIndex(
            model_name='abonoproveedor',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='ventas_abon_estado_1d89b7_idx'),
        ),
    ]
