# Generated by Django 5.2.7 on 2026-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0056_alter_abonopago_forma_pago_alter_notificacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonoproveedor',
            name='proveedor',
            field=models.CharField(help_text='Nombre del proveedor al que se abonará', max_length=255, verbose_name='Proveedor'),
        ),
    ]
