# Generated by Django 5.2.7 on 2026-01-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0055_merge_20260115_1747'),
        ('ventas', '0057_alter_abonoproveedor_proveedor'),
    ]

    operations = [
    ]
