# Generated by Django 5.2.7 on 2026-01-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0057_alter_abonoproveedor_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='requiere_factura_apertura',
            field=models.BooleanField(default=False, help_text='Indica si el cliente requiere factura por el monto de apertura.', verbose_name='Requiere Factura por Apertura'),
        ),
    ]
