# Generated by Django 5.2.7 on 2026-01-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0058_merge_20260118_1936'),
        ('ventas', '0058_ventaviaje_requiere_factura_apertura'),
    ]

    operations = [
    ]
