# Generated by Django 5.2.7 on 2026-01-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0059_merge_20260122_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='metodo_pago_preferencial',
            field=models.BooleanField(default=False, help_text='Si está activo, las ventas nacionales con este proveedor mostrarán la tabla de abonos al proveedor.', verbose_name='Método de Pago Preferencial'),
        ),
    ]
