# Generated by Django 5.2.7 on 2026-01-25 21:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0060_add_metodo_pago_preferencial_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('tipo_vendedor', models.CharField(choices=[('MOSTRADOR', 'Asesor de Mostrador'), ('CAMPO', 'Asesor de Campo'), ('ISLA', 'Asesor de Isla')], default='MOSTRADOR', max_length=20, verbose_name='Tipo de Vendedor')),
                ('total_ventas_mes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Ventas del Mes')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje de Comisión (%)')),
                ('bono_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Bono Extra (1% sobre $500,000+)')),
                ('comision_total_pagada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión Total Pagada')),
                ('comision_total_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión Total Pendiente')),
                ('comision_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión Total')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='comisiones_excel/%Y/%m/', verbose_name='Archivo Excel Generado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_mensuales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Comisión Mensual',
                'verbose_name_plural': 'Comisiones Mensuales',
                'ordering': ['-anio', '-mes', 'vendedor'],
                'indexes': [models.Index(fields=['vendedor', 'mes', 'anio'], name='ventas_comi_vendedo_51eb2e_idx'), models.Index(fields=['tipo_vendedor', 'mes', 'anio'], name='ventas_comi_tipo_ve_0d12a0_idx')],
                'unique_together': {('vendedor', 'mes', 'anio', 'tipo_vendedor')},
            },
        ),
        migrations.CreateModel(
            name='ComisionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('tipo_venta', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('VUELO', 'Vuelo Solitario')], max_length=20, verbose_name='Tipo de Venta')),
                ('monto_base_comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Base para Comisión')),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje Aplicado (%)')),
                ('comision_calculada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión Calculada (100%)')),
                ('comision_pagada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión Pagada')),
                ('comision_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Comisión Pendiente')),
                ('estado_pago_venta', models.CharField(choices=[('PAGADA', 'Pagada al 100%'), ('PENDIENTE', 'Pendiente de Pago')], default='PENDIENTE', max_length=20, verbose_name='Estado de Pago de la Venta')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Desglose detallado de la comisión (tarifa_base, suplementos, tours, impuestos excluidos, etc.)', verbose_name='Detalles de la Comisión')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_ventas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='ventas.ventaviaje', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Comisión de Venta',
                'verbose_name_plural': 'Comisiones de Ventas',
                'indexes': [models.Index(fields=['vendedor', 'mes', 'anio'], name='ventas_comi_vendedo_135b79_idx'), models.Index(fields=['venta'], name='ventas_comi_venta_i_79c21b_idx')],
                'unique_together': {('venta', 'mes', 'anio')},
            },
        ),
    ]
