# Generated by Django 5.2.7 on 2026-01-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0062_crear_solicitud_cancelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comisionventa',
            new_name='ventas_comi_cancela_3f1c91_idx',
            old_name='ventas_comi_cancelada_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudcancelacion',
            new_name='ventas_soli_venta_i_32b4a8_idx',
            old_name='ventas_solic_venta_i_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudcancelacion',
            new_name='ventas_soli_estado_ee1e86_idx',
            old_name='ventas_solic_estado__456def_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudcancelacion',
            new_name='ventas_soli_solicit_ad0eb4_idx',
            old_name='ventas_solic_solicit_789ghi_idx',
        ),
        migrations.AddField(
            model_name='comisionmensual',
            name='ajustado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el ajuste manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_ajustadas', to=settings.AUTH_USER_MODEL, verbose_name='Ajustado Por'),
        ),
        migrations.AddField(
            model_name='comisionmensual',
            name='fecha_ajuste',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se realizó el ajuste manual', null=True, verbose_name='Fecha de Ajuste'),
        ),
        migrations.AddField(
            model_name='comisionmensual',
            name='nota_ajuste',
            field=models.TextField(blank=True, help_text='Justificación o nota sobre el ajuste manual realizado', verbose_name='Nota del Ajuste'),
        ),
        migrations.AddField(
            model_name='comisionmensual',
            name='porcentaje_ajustado_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión ajustado manualmente. Si está presente, sobrescribe el cálculo automático.', max_digits=5, null=True, verbose_name='Porcentaje Ajustado Manualmente (%)'),
        ),
    ]
