# Generated by Django 5.2.7 on 2026-02-03 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0063_agregar_ajuste_manual_comision_isla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonoproveedor',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de pago al proveedor (imagen JPG, PNG o PDF)', null=True, upload_to='comprobantes_proveedor/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante de Abono'),
        ),
    ]
