# Generated by Django 5.2.7 on 2026-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0064_abonoproveedor_comprobante_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaviaje',
            name='apertura_confirmada',
            field=models.BooleanField(default=False, help_text='True solo cuando el contador ha confirmado explícitamente el pago de apertura (y comprobante subido). Para TRN/TAR/DEP la apertura no cuenta en total_pagado hasta que sea True.', verbose_name='Apertura confirmada por contador'),
        ),
    ]
