# Generated by Django 5.2.7 on 2026-02-11 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0068_backfill_usd_ventas_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonopago',
            name='confirmado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Confirmado por Contador'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='fecha_pago',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='abonopago',
            name='forma_pago',
            field=models.CharField(choices=[('TRN', 'Transferencia'), ('EFE', 'Ikki'), ('TAR', 'Tarjeta'), ('DEP', 'Depósito'), ('PPL', 'PayPal/Digital'), ('LIG', 'Liga de Pago'), ('PRO', 'Directo a Proveedor')], db_index=True, default='TRN', max_length=3, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], db_index=True, default='ACTIVA', help_text='Estado general de la venta', max_length=20, verbose_name='Estado de la Venta'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='estado_confirmacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CONFIRMACION', 'En Confirmación'), ('COMPLETADO', 'Completado')], db_index=True, default='PENDIENTE', help_text='Estado de confirmación del pago por el contador', max_length=20, verbose_name='Estado de Confirmación'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='fecha_inicio_viaje',
            field=models.DateField(db_index=True, verbose_name='Fecha de Ida (Inicio de Viaje)'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='fecha_vencimiento_pago',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha Límite de Pago Total'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], db_index=True, default='NAC', max_length=3, verbose_name='Tipo de Viaje (Plantilla de Contrato)'),
        ),
    ]
