# Generated by Django 5.2.7 on 2026-02-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0069_add_db_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutivo',
            name='ultima_contrasena',
        ),
    ]
