# Generated by Django 5.2.7 on 2026-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0070_remove_ultima_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonopago',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AlterField(
            model_name='ventaviaje',
            name='fecha_fin_viaje',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Regreso (Fin de Viaje)'),
        ),
    ]
