# Generated by Django 5.2.7 on 2026-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0071_add_missing_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaviaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional'), ('INT_MXN', 'Internacional MXN')], db_index=True, default='NAC', max_length=7, verbose_name='Tipo de Viaje (Plantilla de Contrato)'),
        ),
    ]
