# Generated by Django 5.2.7 on 2026-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0072_add_int_mxn_tipo_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionventa',
            name='tipo_venta',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('INTERNACIONAL MXN', 'Internacional MXN'), ('VUELO', 'Vuelo Solitario')], max_length=20, verbose_name='Tipo de Venta'),
        ),
    ]
