# Generated by Django 5.2.7 on 2026-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0076_cotizacion_vendedor_adjudicado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsAgencia',
            fields=[
                ('id_usuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('plataforma', models.CharField(max_length=20)),
                ('bot_activo', models.BooleanField(default=True)),
                ('resumen_viaje', models.TextField(blank=True, null=True)),
                ('estado_venta', models.CharField(default='nuevo', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead Agencia',
                'verbose_name_plural': 'Leads Agencia',
                'db_table': 'leads_agencia',
                'managed': False,
            },
        ),
    ]
