# Generated by Django 5.2.7 on 2025-10-22 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('JEFE', 'Jefe (Acceso Total)'), ('CONTADOR', 'Contador (Solo Pagos/Reportes)'), ('VENDEDOR', 'Vendedor (Ventas/Clientes)')], default='VENDEDOR', max_length=10)),
                ('tipo_vendedor', models.CharField(choices=[('OFICINA', 'Oficina'), ('ISLA', 'Isla de Venta'), ('CAMPO', 'Campo / Externo')], default='OFICINA', help_text='Usado para calcular el esquema de comisiones.', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
