# Generated by Django 5.2.7 on 2025-12-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('JEFE', 'Jefe (Acceso Total)'), ('DIRECTOR_GENERAL', 'Director General'), ('DIRECTOR_VENTAS', 'Director de Ventas'), ('DIRECTOR_ADMINISTRATIVO', 'Director Administrativo'), ('GERENTE', 'Gerente'), ('CONTADOR', 'Contador (Solo Pagos/Reportes)'), ('VENDEDOR', 'Asesor (Ventas/Clientes)')], default='VENDEDOR', max_length=25),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_vendedor',
            field=models.CharField(choices=[('MOSTRADOR', 'Asesor de Mostrador'), ('CAMPO', 'Asesor de Campo'), ('ISLA', 'Asesor de Isla')], default='MOSTRADOR', help_text='Usado para calcular el esquema de comisiones. Solo aplica para usuarios con rol Asesor.', max_length=10),
        ),
    ]
