# Generated by Django 5.2.7 on 2026-02-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_migrar_tipos_vendedor'),
        ('ventas', '0068_backfill_usd_ventas_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='oficina',
            field=models.ForeignKey(blank=True, help_text='Solo para rol Gerente: limita la vista a datos de esta oficina.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_gerente', to='ventas.oficina', verbose_name='Oficina asignada'),
        ),
    ]
