# Generated by Django 5.2.7 on 2026-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_agregar_oficina_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='solo_lectura_ventas',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario solo puede ver ventas y el calendario de viajes en el dashboard, sin crear ni modificar nada.', verbose_name='Solo lectura ventas'),
        ),
    ]
