# Generated by Django 5.2.7 on 2025-10-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(help_text='Necesario para el envío de WhatsApp.', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('documento_identificacion', models.CharField(blank=True, help_text='Pasaporte, INE u otra identificación.', max_length=50, null=True, unique=True)),
                ('preferencias_viaje', models.TextField(blank=True, help_text='Notas sobre sus gustos de viaje (Playa, Aventura...).')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
