# Generated by Django 5.2.7 on 2025-11-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cliente_apellido_cliente_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal para Facturación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social / Nombre de la Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC / ID Fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('EMPRESA', 'Empresa')], default='PARTICULAR', max_length=10, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
