# Generated by Django 5.2.7 on 2025-11-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_cliente_direccion_fiscal_cliente_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cotizaciones_generadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de cotizaciones generadas'),
        ),
    ]
