# Generated by Django 5.2.7 on 2025-12-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cliente_cotizaciones_generadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cotizaciones_generadas',
        ),
    ]
