# Generated by Django 5.2.7 on 2025-12-02 05:53

from django.db import migrations


class Migration(migrations.Migration):
    # Esta migración se elimina del flujo principal para evitar la pérdida de datos.
    # Se conserva como marcador vacío para no romper historiales donde se aplicó.
    dependencies = [
        ('crm', '0004_cliente_cotizaciones_generadas'),
    ]

    operations = []
