# Generated by Django 5.2.7 on 2025-12-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_cliente_kilometros_historial'),
        ('crm', '0005_remove_cliente_cotizaciones_generadas'),
    ]

    operations = [
    ]
