# Generated by Django 5.2.7 on 2025-12-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_cliente_kilometros_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialkilometros',
            name='expirado',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento ya fue procesado para expiración.'),
        ),
    ]
