# Generated by Django 5.2.7 on 2025-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_merge_20251202_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialkilometros',
            name='expirado',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento ya fue procesado para expiración.'),
        ),
    ]
