# Generated by Django 5.2.7 on 2025-12-15 16:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_historialkilometros_expirado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionKilometros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('factor_multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción de Kilómetros',
                'verbose_name_plural': 'Promociones de Kilómetros',
                'ordering': ['-creada_en'],
            },
        ),
    ]
