# Generated by Django 5.2.7 on 2025-12-15 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_promocionkilometros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocionkilometros',
            name='factor_multiplicador',
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='alcance',
            field=models.CharField(choices=[('TODAS', 'Todas las ventas'), ('NAC', 'Solo ventas nacionales'), ('INT', 'Solo ventas internacionales')], default='TODAS', max_length=10),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='combinable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='condicion',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CUMPLE', 'Cumpleaños del cliente'), ('MES', 'Mes específico'), ('RANGO', 'Rango de fechas')], default='SIEMPRE', max_length=20),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='monto_tope_mxn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='prioridad',
            field=models.PositiveIntegerField(default=1, help_text='Mayor número = mayor prioridad'),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='requiere_confirmacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='tipo',
            field=models.CharField(choices=[('DESCUENTO', 'Descuento % sobre total')], default='DESCUENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='valor_condicion',
            field=models.CharField(blank=True, help_text='Ej: mes=2, o día/mes 14-02', max_length=20, null=True),
        ),
    ]
