# Generated by Django 5.2.7 on 2025-12-15 17:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_promocionkilometros_factor_multiplicador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocionkilometros',
            name='combinable',
        ),
        migrations.RemoveField(
            model_name='promocionkilometros',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='promocionkilometros',
            name='kilometros_bono',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solo aplica si el tipo es Bonificación de Kilómetros.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='promocionkilometros',
            name='tipo',
            field=models.CharField(choices=[('DESCUENTO', 'Descuento % sobre total'), ('KM', 'Bonificación de Kilómetros')], default='DESCUENTO', max_length=20),
        ),
    ]
