# Generated by Django 5.2.7 on 2025-12-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_promocionkilometros_combinable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa_asociada',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_cliente': 'EMPRESA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='crm.cliente', verbose_name='Empresa Asociada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NS', 'Sin Especificar')], default='NS', max_length=2, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ine_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/ine/', verbose_name='Imagen INE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pasaporte_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Pasaporte'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pasaporte_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de Pasaporte'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_adicional',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Adicional'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='visa_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Visa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='visa_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de Visa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Necesario para el envío de WhatsApp.', max_length=20, unique=True, verbose_name='Teléfono Móvil'),
        ),
    ]
