# Generated by Django 5.2.7 on 2025-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_cliente_empresa_asociada_cliente_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='credito',
            field=models.BooleanField(default=False, help_text='Indica si la empresa tiene línea de crédito', verbose_name='Crédito (si aplica)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='industria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='politicas_viaje_internas',
            field=models.TextField(blank=True, help_text='Políticas y restricciones de viaje de la empresa', null=True, verbose_name='Políticas de Viaje Internas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsable_administrativo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable Administrativo'),
        ),
    ]
