# Generated by Django 5.2.7 on 2025-12-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_cliente_credito_cliente_industria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='monto_credito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de crédito asignado a la empresa (si aplica)', max_digits=12, null=True, verbose_name='Monto de Crédito Asignado'),
        ),
    ]
