# Generated by Django 5.2.7 on 2026-01-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_cliente_monto_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialkilometros',
            name='tipo_evento',
            field=models.CharField(choices=[('COMPRA', 'Compra de servicios'), ('REFERIDO', 'Bonificación por referido'), ('CUMPLE', 'Bonificación por cumpleaños'), ('CAMPANIA', 'Campaña especial'), ('BONO_PROMOCION', 'Bono de promoción'), ('AJUSTE', 'Ajuste manual'), ('REDENCION', 'Redención aplicada'), ('REVERSION_CANCELACION', 'Reversión por cancelación'), ('REVERSION_REDENCION', 'Reversión de redención'), ('EXPIRACION', 'Expiración de kilómetros')], max_length=25),
        ),
    ]
