# Generated by Django 5.2.7 on 2026-01-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_agregar_promociones_personales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocionkilometros',
            name='clientes',
        ),
        migrations.AlterField(
            model_name='promocionkilometros',
            name='alcance',
            field=models.CharField(choices=[('TODAS', 'Todas las ventas'), ('NAC', 'Solo ventas nacionales'), ('INT', 'Solo ventas internacionales')], default='TODAS', max_length=10),
        ),
    ]
