# Generated by Django 5.2.7 on 2026-01-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_promocionkilometros_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocionkilometros',
            name='clientes',
            field=models.ManyToManyField(blank=True, help_text="Selecciona uno o más clientes. Solo aplica si el alcance es 'Cliente(s) específico(s)'.", related_name='promociones_personales', to='crm.cliente', verbose_name='Clientes específicos'),
        ),
        migrations.AlterField(
            model_name='promocionkilometros',
            name='alcance',
            field=models.CharField(choices=[('TODAS', 'Todas las ventas'), ('NAC', 'Solo ventas nacionales'), ('INT', 'Solo ventas internacionales'), ('CLIENTE_ESPECIFICO', 'Cliente(s) específico(s)')], default='TODAS', max_length=20),
        ),
    ]
