# Generated by Django 5.2.7 on 2026-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_promocionkilometros_clientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Razón Social / Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='participa_kilometros',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Participa en Kilómetros Movums'),
        ),
    ]
